/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ACascader: typeof import('@arco-design/web-vue')['Cascader']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ARow: typeof import('@arco-design/web-vue')['Row']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VButton: typeof import('./../components/v-button/v-button.vue')['default']
    VForm: typeof import('./../components/v-form/v-form.vue')['default']
    VFormItem: typeof import('./../components/v-form/v-form-item.vue')['default']
    VLoading: typeof import('./../components/v-loading/v-loading.vue')['default']
    VUpload: typeof import('./../components/v-upload/v-upload.vue')['default']
  }
}
